version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu
shallow_clone: true
install:
- sh: >-
    nvm install 14


    nvm use 14


    node -v


    npm -v
build_script:
- sh: >-
    docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build


    cd src/TinyBlog.Web/


    npm install


    npm run testcafe


    cd ../..


    docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
test: off
