version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Ubuntu1804
configuration: Release
shallow_clone: true
build_script:
- sh: dotnet build -c=Release src/TinyBlog.Web/TinyBlog.Web.csproj
test_script:
- sh: dotnet test -c=Release tests/TinyBlog.Tests/TinyBlog.Tests.csproj