version: '3'

services:
  tinyblog:
    image: vladikan/tinyblog:latest
    container_name: "tinyblog"
    hostname: "tinyblog"
    restart: always

    logging:
      driver: json-file
      options:
          max-size: "5m"
          max-file: "5"

    environment:
      - WEB_ConnectionStrings__Blog
      
      - WEB_Auth__Secret
      - WEB_Auth__Issuer
      - WEB_Auth__Audience

      - WEB_SiteSettings__DefaultCacheDuration

      - WEB_Smtp__Enabled
      - WEB_Smtp__UseSsl
      - WEB_Smtp__Address
      - WEB_Smtp__Port
      - WEB_Smtp__Username
      - WEB_Smtp__Password
      - WEB_Smtp__FromEmail