version: '3'

services:
  tinyblog:
    build: .
    ports:
      - 8080:80
    depends_on:
      - mongo
    environment:
      - WEB_ConnectionStrings__Blog=mongodb://webapp:password@mongo/blog

  mongo:
    image: mongo:3.6
    container_name: "mongo"
    hostname: "mongo"
    restart: always
    ports:
      - 27017:27017
    volumes:
      #- ./var:/data/db
      - ./dev/mongo:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=blog
  
#  mongo-express:
#    image: mongo-express:latest
#    container_name: "mongo-express"
#    hostname: "mongo-express"
#    restart: always
#    ports:
#      - 8081:8081
#    depends_on:
#      - mongo
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin